- name: Configure the BLUE Server
  hosts: tag_Deployment_Blue
  become: yes
  tasks:
    - name: Install httpd
      dnf: { name: httpd, state: present }
    - name: Copy index file
      copy: { src: files/index_blue.html, dest: /var/www/html/index.html }
    - name: Start httpd
      service: { name: httpd, state: started, enabled: yes }
